CREATE TABLE PRODUTOS(
    CODIGO VARCHAR2(10) PRIMARY KEY,
    DESCRITOR VARCHAR2(100) NULL,
    SABOR VARCHAR2(50) NULL,
    TAMANHO VARCHAR2(50) NULL,
    EMBALAGEM VARCHAR2(50) NULL,
    PRECO_LISTA NUMBER(10,2) NULL
);

CREATE TABLE VENDEDORES(
    MATRICULA VARCHAR2(5) PRIMARY KEY,
    NOME VARCHAR2(100)NULL,
    BAIRRO VARCHAR2(50)NULL,
    COMISSAO NUMBER(10,2) NULL,
    DATA_ADMISSAO DATE NULL,
    FERIAS INTEGER NULL
);

CREATE TABLE CLIENTE (
    CPF VARCHAR2(11) PRIMARY KEY,
    NOME VARCHAR2(100),
    ENDERECO VARCHAR2(150),
    BAIRRO VARCHAR2(50),
    CIDADE VARCHAR2(50),
    ESTADO VARCHAR2(50),
    CEP VARCHAR2(8),
    DATA_NASCIMENTO DATE,
    IDADE NUMBER(3),
    GENERO CHAR(1),
    LIMITE_CREDITO NUMBER(10, 2), 
    VOLUME_COMPRA NUMBER(10, 2),
    PRIMEIRA_COMPRA CHAR(1)
);

CREATE TABLE TABELA_DE_VENDAS (
    NUMERO VARCHAR2(5) PRIMARY KEY,
    DATA_VENDA DATE NULL,
    CPF VARCHAR2(11) NOT NULL,
    MATRICULA VARCHAR2(5) NOT NULL,
    IMPOSTO NUMBER(10, 2),
    CONSTRAINT FK_VENDAS_CLIENTE FOREIGN KEY (CPF) REFERENCES CLIENTE(CPF),
    CONSTRAINT FK_VENDAS_VENDEDOR FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES(MATRICULA)
);

